key_managerkey_homepage:
    path:     /
    defaults: { _controller: keyManagerkeyBundle:homePage:index }

login:
    path:     /login
    defaults: { _controller: keyManagerkeyBundle:homePage:login }

login_check:
    pattern:    /login_check

logout:
    path: /logout

signup:
    path: /signup
    defaults: { _controller: keyManagerkeyBundle:homePage:signup }

ClientProfile_homePage:
    path: /login/clientProfile
    defaults: { _controller: keyManagerkeyBundle:clientPage:clientProfile }

AddClient_ClientProfile:
    path: /login/clientProfile/addClient
    defaults: { _controller: keyManagerkeyBundle:clientPage:addClient }

SearchClient_ClientProfile:
    path: /login/clientProfile/searchClient/{id}
    defaults: { _controller: keyManagerkeyBundle:clientPage:searchClient, id: 1 }

UpdateClient_ClientProfile:
    path: /login/clientProfile/UpdateClient/{id}
    defaults: { _controller: keyManagerkeyBundle:clientPage:updateClient, id : 1 }
    requirements:
            _method:  GET|POST
            id: \d+

DeleteClient_ClientProfile:
    path: /login/clientProfile/DeleteClient/{id}
    defaults: { _controller: keyManagerkeyBundle:clientPage:DeleteClient, id: 0 }
    requirements:
                _method:  GET|POST
                id: \d+

ClefProfile_homePage:
    path: /login/clefProfile
    defaults: { _controller: keyManagerkeyBundle:clefPage:clefProfile }

AddKey_ClefProfile:
    path: /login/clefProfile/addKey
    defaults: { _controller: keyManagerkeyBundle:clefPage:addKey }

UpdateKey_ClefProfile:
    path: /login/clefProfile/updateKey/{id}
    defaults: { _controller: keyManagerkeyBundle:clefPage:updateKey, id: 1 }

tpe_ClefProfile:
    path: /login/clefProfile/tpe
    defaults: { _controller: keyManagerkeyBundle:clefPage:tpe }

TpeProfile_homePage:
    path: /login/tpeProfile
    defaults: { _controller: keyManagerkeyBundle:tpePage:tpeProfile }

AddTpe_TpeProfile:
    path: /login/tpeProfile/addTpe/{id}
    defaults: { _controller: keyManagerkeyBundle:tpePage:addTpe, id: 0 }

UpdateTpe_TpeProfile:
    path: /login/tpeProfile/updateTpe/{id}
    defaults: { _controller: keyManagerkeyBundle:tpePage:updateTpe, id: 1 }


HistoriqueProfile_homePage:
    path: /login/historiqueProfile
    defaults: { _controller: keyManagerkeyBundle:historiquePage:historiqueProfile }





