<?php

namespace keyManager\keyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tpenewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tpenewRepository extends EntityRepository
{
}
