<?php

namespace keyManager\keyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tpenewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tpenewRepository extends EntityRepository
{
    public function findByclientname($id)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.clientNew = :id')
            ->setParameter('id',$id);
        return $qb->getQuery()
            ->getResult();

    }

    public function findByClientID($clientNew_id)
    {
//        $qb2 = $this->getEntityManager()->createQuery("
//            SELECT tpenew
//            FROM keyManagerkeyBundle:tpenew tpenew
//            left JOIN tpenew.clientNew ClientNew
//            WHERE ClientNew.id = :clientNew_id
//        ")->setParameter('clientNew_id', $clientNew_id);

        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->leftJoin('t.clientNew', 'ClientNew')
            ->where('ClientNew.id = :clientNew_id')
            ->setParameter('clientNew_id', $clientNew_id);

        return $qb->getQuery()->getResult();
    }

    public function findbycustom($clientNew)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.tpeNum')
            ->where('t.clientNew = :clientNew')
            ->setParameter('clientNew', $clientNew);

        return $qb->getQuery()->getResult();
    }
}
