keyManager\keyBundle\Entity\KeyNew:
    type: entity
    table: null
    repositoryClass: keyManager\keyBundle\Entity\KeyNewRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        startDate:
            type: date
        endDate:
            type: date
        keyName:
            type: string
            length: '50'
        keyValid:
            type: boolean

    oneToOne:
        tpenew:
            targetEntity: tpenew
            joinColum:
                nullable: false

#    manyToOne:
#            tpenew:
#                targetEntity: tpenew
#                inversedBy: keyNews
#                joinColum:
#                    name: tpenew_id
#                    referencedColumnName: id

    lifecycleCallbacks: {  }
