keyManager\keyBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        isActive:
            type: boolean

    #ManyToMany:
     #   roles:
      #      targetEntity: Role
       #     inversedBy: users

    lifecycleCallbacks: {  }
